"""updated documen table , removed unique constraint

Revision ID: dd902c74bada
Revises: ff1e6f4a4621
Create Date: 2024-07-01 16:37:03.629259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd902c74bada'
down_revision: Union[str, None] = 'ff1e6f4a4621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_vector_db_id_key', 'documents', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('documents_vector_db_id_key', 'documents', ['vector_db_id'])
    # ### end Alembic commands ###
